language: c
sudo: false
compiler:
 - gcc
addons:
 apt:
  packages:
   - pkg-config
before_install:
 - export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
 - export LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
 - export LD_RUN_PATH=$HOME/local/lib:$LD_RUN_PATH
 - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
 - export PATH=.travis:$PATH
script:
 - autoreconf --install -W none
 - ./configure
 - make
